### ISSUE TITLE
Too much battery consumption

### ISSUE THREAD

**Issue by serrq** [KoalaSat/nostros#315]
As this image shows with only 4 active relays I had 152 mAh in battery drain for only 18 minutes in foreground. A regular mp3 app is around 80 mAh/hour.

I need to know if Nostros properly kills itself when I close it.
If not then I need of "Quit" button in order to communicate to app its shutdown (to save battery).

My target is drain battery only when I actively use the app (only in foreground).

![Screenshot_2023-02-12-07-51-11-80_0ba066473b79d6e213a1f6f52505e2ee](https://user-images.githubusercontent.com/113377431/218297390-03db5c1f-b819-417b-ad34-6f5446449729.jpg)

**Comment by KoalaSat** [comment]
If by when you close it means to kill it from memory, the app wont be running anymore, keep in mind all Android devices the bottom right option is not "Close" but "Minimize"

**Comment by KoalaSat** [comment]
This is not in nostros, it's on Android, and there is no way to manage this, all nostr clients face this issue and honestly there is no easy way to solve it since, first because of the technology the nostr protocol requires, and secondly becuase the limitations Android impose to installed apps.

I'm also an Android user and I recommend you to always take care of this with any app either nostr related or not.

**Comment by KoalaSat** [comment]
Thanks for reporting! I'll continue investigating on best ways to save battery and data, or maybe a light mode? I have to think about that

**Comment by KoalaSat** [comment]
No, one button, if can maybe figure out a way to shoot down some parts of the app where you lose some experience but gain battery/data

**Comment by KoalaSat** [comment]
I received several good reports from users, so far it looks we are doing our best, taking into consideration what the technology allow us. I'll close this, is this becomes again a problem let's open it again
