### ISSUE TITLE
copy text in posts (feature req.)

### ISSUE THREAD

**Issue by Wjxfi** [KoalaSat/nostros#362]
I get recommended posts in Japanese, and I want to know what it says, but I can't copy it.

If you long press on the text that I wrote, it will be highlighted in blue and it will be possible to copy it. I want to be able to do the same in the application

**Comment by KoalaSat** [comment]
Right now you can long press the post and the content will be copied to your clipboard, the only missing part is highlighting the text

**Comment by KoalaSat** [comment]
Implemented, will be included in the next release

**Comment by KoalaSat** [comment]
I have been testing it on my local for a day and honestly O don't know what to think about it, sometimes the text gets selected just because I'm scrolling over it, I don't think there is a way to control this, I'll give it another try and see what people think but not 100% happy

I also implemented a full copy text button on a note options drawer, not sure if with that would be enough?

**Comment by KoalaSat** [comment]
I just released the latest version with the selection activated, let's see what's the feedback we get
