### ISSUE TITLE
unable to click on "+" to add relays

### ISSUE THREAD

**Issue by KruyKaze** [KoalaSat/nostros#52]
v0.1.9.3-alpha [Latest](https://github.com/KoalaSat/nostros/releases/latest)
Thanks !

**Comment by KoalaSat** [comment]
Hi @KruyKaze I think this might be due to not enough info about the relays view. 

For now on alpha version you can only have  one active relay, so in order to choose other one you need to first delete the active one. Please let me know if this is your case.

I'm actually working on an UI redesign and I'll have this into consideration.

**Comment by KruyKaze** [comment]
Yes I can add one when I remove one .thanks

Dec 19, 2022 15:54:12 KoalaSat ***@***.***>:
